# Generated by Django 5.1.3 on 2024-12-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0004_studytip_alter_user_name_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(help_text="Duration (e.g., '2 hours')", max_length=50)),
                ('topics', models.TextField(blank=True, help_text="Comma-separated topics, e.g., 'Topic 1, Topic 2'")),
            ],
        ),
    ]
