# Generated by Django 5.1.3 on 2024-12-13 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0006_defaulttask_usertask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulttask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usertask',
            name='default_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tasks', to='studyplanner.defaulttask'),
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='time',
            field=models.CharField(blank=True, help_text="e.g., '6:00 AM - 7:00 AM'", max_length=50),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='time',
            field=models.CharField(blank=True, help_text="e.g., '6:00 AM - 7:00 AM'", max_length=50),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='studyplanner.user'),
        ),
    ]
