# Generated by Django 5.1.3 on 2024-12-13 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0007_remove_defaulttask_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='default_task',
        ),
        migrations.AddField(
            model_name='defaulttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='time',
            field=models.CharField(blank=True, help_text="Time, e.g., '6:00 AM - 7:00 AM'", max_length=50),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='time',
            field=models.CharField(blank=True, help_text="Time, e.g., '6:00 AM - 7:00 AM'", max_length=50),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='studyplanner.user'),
        ),
    ]
