# Generated by Django 5.1.3 on 2024-12-14 06:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0008_remove_usertask_default_task_defaulttask_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserTaskAdmin',
            fields=[
                ('usertask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studyplanner.usertask')),
            ],
            bases=('studyplanner.usertask',),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='defaulttask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='time',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='title',
        ),
        migrations.AddField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studyplanner.defaulttask'),
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
