# Generated by Django 5.1.3 on 2024-12-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0009_sign_in_usertaskadmin_alter_usertask_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaulttask',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
