# Generated by Django 5.1.3 on 2024-12-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyplanner', '0010_alter_defaulttask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='defaulttask',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
